//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/Msi/RiderProjects/Satuk/Satuk/Satuk.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SatukParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ISatukVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SatukParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] SatukParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SatukParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg([NotNull] SatukParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>display</c>
	/// labeled alternative in <see cref="SatukParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDisplay([NotNull] SatukParser.DisplayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SatukParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] SatukParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>boolAss</c>
	/// labeled alternative in <see cref="SatukParser.assign_bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolAss([NotNull] SatukParser.BoolAssContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>boolLogAss</c>
	/// labeled alternative in <see cref="SatukParser.assign_bool_logical"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolLogAss([NotNull] SatukParser.BoolLogAssContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>boolDynAss</c>
	/// labeled alternative in <see cref="SatukParser.assign_bool_dynamic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolDynAss([NotNull] SatukParser.BoolDynAssContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stringAss</c>
	/// labeled alternative in <see cref="SatukParser.assign_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringAss([NotNull] SatukParser.StringAssContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stringDynAss</c>
	/// labeled alternative in <see cref="SatukParser.assign_string_dynamic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringDynAss([NotNull] SatukParser.StringDynAssContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>charAss</c>
	/// labeled alternative in <see cref="SatukParser.assign_char"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharAss([NotNull] SatukParser.CharAssContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>charDynAss</c>
	/// labeled alternative in <see cref="SatukParser.assign_char_dynamic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharDynAss([NotNull] SatukParser.CharDynAssContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>intConstAss</c>
	/// labeled alternative in <see cref="SatukParser.assign_int_constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntConstAss([NotNull] SatukParser.IntConstAssContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>intArAss</c>
	/// labeled alternative in <see cref="SatukParser.assign_int_ar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntArAss([NotNull] SatukParser.IntArAssContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>intDynAss</c>
	/// labeled alternative in <see cref="SatukParser.assign_int_dynamic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntDynAss([NotNull] SatukParser.IntDynAssContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>floatConstAss</c>
	/// labeled alternative in <see cref="SatukParser.assign_float_constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatConstAss([NotNull] SatukParser.FloatConstAssContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>floatDynAss</c>
	/// labeled alternative in <see cref="SatukParser.assign_float_dynamic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatDynAss([NotNull] SatukParser.FloatDynAssContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>floatArAss</c>
	/// labeled alternative in <see cref="SatukParser.assign_float_ar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatArAss([NotNull] SatukParser.FloatArAssContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>classAss</c>
	/// labeled alternative in <see cref="SatukParser.assignment_class"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassAss([NotNull] SatukParser.ClassAssContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SatukParser.assignment_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_function([NotNull] SatukParser.Assignment_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numberArithm</c>
	/// labeled alternative in <see cref="SatukParser.arithmetics"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberArithm([NotNull] SatukParser.NumberArithmContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parenArithm</c>
	/// labeled alternative in <see cref="SatukParser.arithmetics"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenArithm([NotNull] SatukParser.ParenArithmContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opArithm</c>
	/// labeled alternative in <see cref="SatukParser.arithmetics"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpArithm([NotNull] SatukParser.OpArithmContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opArithmInt</c>
	/// labeled alternative in <see cref="SatukParser.arithmetics_int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpArithmInt([NotNull] SatukParser.OpArithmIntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>opArithmFloat</c>
	/// labeled alternative in <see cref="SatukParser.arithmetics_float"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpArithmFloat([NotNull] SatukParser.OpArithmFloatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SatukParser.mutators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMutators([NotNull] SatukParser.MutatorsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>incInt</c>
	/// labeled alternative in <see cref="SatukParser.int_inc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncInt([NotNull] SatukParser.IncIntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>incFloat</c>
	/// labeled alternative in <see cref="SatukParser.float_inc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncFloat([NotNull] SatukParser.IncFloatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>decInt</c>
	/// labeled alternative in <see cref="SatukParser.int_dec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecInt([NotNull] SatukParser.DecIntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>decFloat</c>
	/// labeled alternative in <see cref="SatukParser.float_dec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecFloat([NotNull] SatukParser.DecFloatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>incVar</c>
	/// labeled alternative in <see cref="SatukParser.variable_inc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncVar([NotNull] SatukParser.IncVarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>decVar</c>
	/// labeled alternative in <see cref="SatukParser.variable_dec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecVar([NotNull] SatukParser.DecVarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SatukParser.logical_instructions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogical_instructions([NotNull] SatukParser.Logical_instructionsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>logBool</c>
	/// labeled alternative in <see cref="SatukParser.logical_bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogBool([NotNull] SatukParser.LogBoolContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>logNum</c>
	/// labeled alternative in <see cref="SatukParser.logical_numeric"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogNum([NotNull] SatukParser.LogNumContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>logText</c>
	/// labeled alternative in <see cref="SatukParser.logical_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogText([NotNull] SatukParser.LogTextContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>logVar</c>
	/// labeled alternative in <see cref="SatukParser.logical_var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogVar([NotNull] SatukParser.LogVarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SatukParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_statement([NotNull] SatukParser.If_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SatukParser.loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoop([NotNull] SatukParser.LoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SatukParser.print_content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrint_content([NotNull] SatukParser.Print_contentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SatukParser.functions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctions([NotNull] SatukParser.FunctionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SatukParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] SatukParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>construct</c>
	/// labeled alternative in <see cref="SatukParser.constructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstruct([NotNull] SatukParser.ConstructContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SatukParser.return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn([NotNull] SatukParser.ReturnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SatukParser.class"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass([NotNull] SatukParser.ClassContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SatukParser.execute_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExecute_function([NotNull] SatukParser.Execute_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>funcVoid</c>
	/// labeled alternative in <see cref="SatukParser.void_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncVoid([NotNull] SatukParser.FuncVoidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>funcInt</c>
	/// labeled alternative in <see cref="SatukParser.int_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncInt([NotNull] SatukParser.FuncIntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>funcFloat</c>
	/// labeled alternative in <see cref="SatukParser.float_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncFloat([NotNull] SatukParser.FuncFloatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>funcString</c>
	/// labeled alternative in <see cref="SatukParser.string_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncString([NotNull] SatukParser.FuncStringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>funcChar</c>
	/// labeled alternative in <see cref="SatukParser.char_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncChar([NotNull] SatukParser.FuncCharContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>funcBool</c>
	/// labeled alternative in <see cref="SatukParser.bool_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncBool([NotNull] SatukParser.FuncBoolContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>funcVar</c>
	/// labeled alternative in <see cref="SatukParser.variable_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncVar([NotNull] SatukParser.FuncVarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SatukParser.void_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVoid_return([NotNull] SatukParser.Void_returnContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>retInt</c>
	/// labeled alternative in <see cref="SatukParser.int_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRetInt([NotNull] SatukParser.RetIntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>retFloat</c>
	/// labeled alternative in <see cref="SatukParser.float_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRetFloat([NotNull] SatukParser.RetFloatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>retString</c>
	/// labeled alternative in <see cref="SatukParser.string_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRetString([NotNull] SatukParser.RetStringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>retChar</c>
	/// labeled alternative in <see cref="SatukParser.char_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRetChar([NotNull] SatukParser.RetCharContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>retBool</c>
	/// labeled alternative in <see cref="SatukParser.bool_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRetBool([NotNull] SatukParser.RetBoolContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>retVar</c>
	/// labeled alternative in <see cref="SatukParser.variable_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRetVar([NotNull] SatukParser.RetVarContext context);
}
