//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/Msi/RiderProjects/Satuk/Satuk/Satuk.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISatukListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class SatukBaseListener : ISatukListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SatukParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] SatukParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SatukParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] SatukParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SatukParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] SatukParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SatukParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] SatukParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>display</c>
	/// labeled alternative in <see cref="SatukParser.print"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDisplay([NotNull] SatukParser.DisplayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>display</c>
	/// labeled alternative in <see cref="SatukParser.print"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDisplay([NotNull] SatukParser.DisplayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>displayString</c>
	/// labeled alternative in <see cref="SatukParser.print_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDisplayString([NotNull] SatukParser.DisplayStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>displayString</c>
	/// labeled alternative in <see cref="SatukParser.print_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDisplayString([NotNull] SatukParser.DisplayStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>print_variable</c>
	/// labeled alternative in <see cref="SatukParser.print_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint_variable([NotNull] SatukParser.Print_variableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>print_variable</c>
	/// labeled alternative in <see cref="SatukParser.print_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint_variable([NotNull] SatukParser.Print_variableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>print_char</c>
	/// labeled alternative in <see cref="SatukParser.print_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint_char([NotNull] SatukParser.Print_charContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>print_char</c>
	/// labeled alternative in <see cref="SatukParser.print_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint_char([NotNull] SatukParser.Print_charContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>print_int</c>
	/// labeled alternative in <see cref="SatukParser.print_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint_int([NotNull] SatukParser.Print_intContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>print_int</c>
	/// labeled alternative in <see cref="SatukParser.print_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint_int([NotNull] SatukParser.Print_intContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>print_float</c>
	/// labeled alternative in <see cref="SatukParser.print_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint_float([NotNull] SatukParser.Print_floatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>print_float</c>
	/// labeled alternative in <see cref="SatukParser.print_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint_float([NotNull] SatukParser.Print_floatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>print_bool</c>
	/// labeled alternative in <see cref="SatukParser.print_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint_bool([NotNull] SatukParser.Print_boolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>print_bool</c>
	/// labeled alternative in <see cref="SatukParser.print_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint_bool([NotNull] SatukParser.Print_boolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>print_arithmetics</c>
	/// labeled alternative in <see cref="SatukParser.print_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint_arithmetics([NotNull] SatukParser.Print_arithmeticsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>print_arithmetics</c>
	/// labeled alternative in <see cref="SatukParser.print_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint_arithmetics([NotNull] SatukParser.Print_arithmeticsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>print_logicalInstructions</c>
	/// labeled alternative in <see cref="SatukParser.print_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint_logicalInstructions([NotNull] SatukParser.Print_logicalInstructionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>print_logicalInstructions</c>
	/// labeled alternative in <see cref="SatukParser.print_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint_logicalInstructions([NotNull] SatukParser.Print_logicalInstructionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ArAss</c>
	/// labeled alternative in <see cref="SatukParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArAss([NotNull] SatukParser.ArAssContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ArAss</c>
	/// labeled alternative in <see cref="SatukParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArAss([NotNull] SatukParser.ArAssContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>boolAss</c>
	/// labeled alternative in <see cref="SatukParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolAss([NotNull] SatukParser.BoolAssContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>boolAss</c>
	/// labeled alternative in <see cref="SatukParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolAss([NotNull] SatukParser.BoolAssContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>stringAss</c>
	/// labeled alternative in <see cref="SatukParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringAss([NotNull] SatukParser.StringAssContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>stringAss</c>
	/// labeled alternative in <see cref="SatukParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringAss([NotNull] SatukParser.StringAssContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>charAss</c>
	/// labeled alternative in <see cref="SatukParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCharAss([NotNull] SatukParser.CharAssContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>charAss</c>
	/// labeled alternative in <see cref="SatukParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCharAss([NotNull] SatukParser.CharAssContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>intConstAss</c>
	/// labeled alternative in <see cref="SatukParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntConstAss([NotNull] SatukParser.IntConstAssContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>intConstAss</c>
	/// labeled alternative in <see cref="SatukParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntConstAss([NotNull] SatukParser.IntConstAssContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>varDynAss</c>
	/// labeled alternative in <see cref="SatukParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDynAss([NotNull] SatukParser.VarDynAssContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>varDynAss</c>
	/// labeled alternative in <see cref="SatukParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDynAss([NotNull] SatukParser.VarDynAssContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>floatConstAss</c>
	/// labeled alternative in <see cref="SatukParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloatConstAss([NotNull] SatukParser.FloatConstAssContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>floatConstAss</c>
	/// labeled alternative in <see cref="SatukParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloatConstAss([NotNull] SatukParser.FloatConstAssContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>classAss</c>
	/// labeled alternative in <see cref="SatukParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassAss([NotNull] SatukParser.ClassAssContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>classAss</c>
	/// labeled alternative in <see cref="SatukParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassAss([NotNull] SatukParser.ClassAssContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SatukParser.assignment_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment_function([NotNull] SatukParser.Assignment_functionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SatukParser.assignment_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment_function([NotNull] SatukParser.Assignment_functionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>numberArithm</c>
	/// labeled alternative in <see cref="SatukParser.arithmetics"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumberArithm([NotNull] SatukParser.NumberArithmContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>numberArithm</c>
	/// labeled alternative in <see cref="SatukParser.arithmetics"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumberArithm([NotNull] SatukParser.NumberArithmContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>parenArithm</c>
	/// labeled alternative in <see cref="SatukParser.arithmetics"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenArithm([NotNull] SatukParser.ParenArithmContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>parenArithm</c>
	/// labeled alternative in <see cref="SatukParser.arithmetics"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenArithm([NotNull] SatukParser.ParenArithmContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>opArithm</c>
	/// labeled alternative in <see cref="SatukParser.arithmetics"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpArithm([NotNull] SatukParser.OpArithmContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>opArithm</c>
	/// labeled alternative in <see cref="SatukParser.arithmetics"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpArithm([NotNull] SatukParser.OpArithmContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>incVar</c>
	/// labeled alternative in <see cref="SatukParser.mutators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncVar([NotNull] SatukParser.IncVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>incVar</c>
	/// labeled alternative in <see cref="SatukParser.mutators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncVar([NotNull] SatukParser.IncVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>decVar</c>
	/// labeled alternative in <see cref="SatukParser.mutators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecVar([NotNull] SatukParser.DecVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>decVar</c>
	/// labeled alternative in <see cref="SatukParser.mutators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecVar([NotNull] SatukParser.DecVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>notLogical</c>
	/// labeled alternative in <see cref="SatukParser.logical_instructions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNotLogical([NotNull] SatukParser.NotLogicalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>notLogical</c>
	/// labeled alternative in <see cref="SatukParser.logical_instructions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNotLogical([NotNull] SatukParser.NotLogicalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>opLogical</c>
	/// labeled alternative in <see cref="SatukParser.logical_instructions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpLogical([NotNull] SatukParser.OpLogicalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>opLogical</c>
	/// labeled alternative in <see cref="SatukParser.logical_instructions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpLogical([NotNull] SatukParser.OpLogicalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>varLogical</c>
	/// labeled alternative in <see cref="SatukParser.logical_instructions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarLogical([NotNull] SatukParser.VarLogicalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>varLogical</c>
	/// labeled alternative in <see cref="SatukParser.logical_instructions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarLogical([NotNull] SatukParser.VarLogicalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SatukParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_statement([NotNull] SatukParser.If_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SatukParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_statement([NotNull] SatukParser.If_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SatukParser.loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoop([NotNull] SatukParser.LoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SatukParser.loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoop([NotNull] SatukParser.LoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SatukParser.functions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctions([NotNull] SatukParser.FunctionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SatukParser.functions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctions([NotNull] SatukParser.FunctionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SatukParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] SatukParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SatukParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] SatukParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>construct</c>
	/// labeled alternative in <see cref="SatukParser.constructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstruct([NotNull] SatukParser.ConstructContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>construct</c>
	/// labeled alternative in <see cref="SatukParser.constructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstruct([NotNull] SatukParser.ConstructContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SatukParser.return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturn([NotNull] SatukParser.ReturnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SatukParser.return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturn([NotNull] SatukParser.ReturnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SatukParser.class"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass([NotNull] SatukParser.ClassContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SatukParser.class"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass([NotNull] SatukParser.ClassContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SatukParser.execute_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExecute_function([NotNull] SatukParser.Execute_functionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SatukParser.execute_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExecute_function([NotNull] SatukParser.Execute_functionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>funcVoid</c>
	/// labeled alternative in <see cref="SatukParser.void_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncVoid([NotNull] SatukParser.FuncVoidContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>funcVoid</c>
	/// labeled alternative in <see cref="SatukParser.void_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncVoid([NotNull] SatukParser.FuncVoidContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>funcInt</c>
	/// labeled alternative in <see cref="SatukParser.int_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncInt([NotNull] SatukParser.FuncIntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>funcInt</c>
	/// labeled alternative in <see cref="SatukParser.int_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncInt([NotNull] SatukParser.FuncIntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>funcFloat</c>
	/// labeled alternative in <see cref="SatukParser.float_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncFloat([NotNull] SatukParser.FuncFloatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>funcFloat</c>
	/// labeled alternative in <see cref="SatukParser.float_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncFloat([NotNull] SatukParser.FuncFloatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>funcString</c>
	/// labeled alternative in <see cref="SatukParser.string_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncString([NotNull] SatukParser.FuncStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>funcString</c>
	/// labeled alternative in <see cref="SatukParser.string_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncString([NotNull] SatukParser.FuncStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>funcChar</c>
	/// labeled alternative in <see cref="SatukParser.char_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncChar([NotNull] SatukParser.FuncCharContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>funcChar</c>
	/// labeled alternative in <see cref="SatukParser.char_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncChar([NotNull] SatukParser.FuncCharContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>funcBool</c>
	/// labeled alternative in <see cref="SatukParser.bool_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncBool([NotNull] SatukParser.FuncBoolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>funcBool</c>
	/// labeled alternative in <see cref="SatukParser.bool_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncBool([NotNull] SatukParser.FuncBoolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>funcVar</c>
	/// labeled alternative in <see cref="SatukParser.variable_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncVar([NotNull] SatukParser.FuncVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>funcVar</c>
	/// labeled alternative in <see cref="SatukParser.variable_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncVar([NotNull] SatukParser.FuncVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SatukParser.void_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVoid_return([NotNull] SatukParser.Void_returnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SatukParser.void_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVoid_return([NotNull] SatukParser.Void_returnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>retInt</c>
	/// labeled alternative in <see cref="SatukParser.int_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRetInt([NotNull] SatukParser.RetIntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>retInt</c>
	/// labeled alternative in <see cref="SatukParser.int_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRetInt([NotNull] SatukParser.RetIntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>retFloat</c>
	/// labeled alternative in <see cref="SatukParser.float_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRetFloat([NotNull] SatukParser.RetFloatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>retFloat</c>
	/// labeled alternative in <see cref="SatukParser.float_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRetFloat([NotNull] SatukParser.RetFloatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>retString</c>
	/// labeled alternative in <see cref="SatukParser.string_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRetString([NotNull] SatukParser.RetStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>retString</c>
	/// labeled alternative in <see cref="SatukParser.string_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRetString([NotNull] SatukParser.RetStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>retChar</c>
	/// labeled alternative in <see cref="SatukParser.char_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRetChar([NotNull] SatukParser.RetCharContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>retChar</c>
	/// labeled alternative in <see cref="SatukParser.char_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRetChar([NotNull] SatukParser.RetCharContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>retBool</c>
	/// labeled alternative in <see cref="SatukParser.bool_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRetBool([NotNull] SatukParser.RetBoolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>retBool</c>
	/// labeled alternative in <see cref="SatukParser.bool_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRetBool([NotNull] SatukParser.RetBoolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>retVar</c>
	/// labeled alternative in <see cref="SatukParser.variable_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRetVar([NotNull] SatukParser.RetVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>retVar</c>
	/// labeled alternative in <see cref="SatukParser.variable_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRetVar([NotNull] SatukParser.RetVarContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
